/**
 * Generates the embedded collab-web dist module used by compiled binaries.
 *
 * Bun 1.3.x (the pinned runtime) has no working `Bun.build({ embed })`
 * directory support (embeddedFiles stays empty; glob embeds fail with
 * ModuleNotFound), so the dist is baked into the bundle the boring way: every
 * file is base64-encoded into a generated TS module that ships with the
 * compiled executable. `core-mode` materializes those bytes into a
 * content-hashed cache directory on first start, so a compiled `omp --mode
 * core` needs no dist checkout and no environment variable.
 *
 * The checked-in form of the generated file is an empty stub; the real
 * contents exist only between `generate` and `reset` inside a binary build.
 */

import * as fs from "node:fs/promises";
import * as path from "node:path";

const GENERATED_REL = path.join("src", "collab", "embedded-collab-web.generated.ts");

const STUB = `// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY
// See scripts/embed-collab-web.ts

/** Collab web dist files baked into compiled binaries: relative path -> base64. */
export const EMBEDDED_COLLAB_WEB_FILES: Record<string, string> = {};

/** Content hash of the embedded dist; used as the materialization cache key. */
export const EMBEDDED_COLLAB_WEB_VERSION = "stub";
`;

async function scanFiles(dir: string, prefix: string): Promise<string[]> {
	const entries = await fs.readdir(dir, { withFileTypes: true });
	const out: string[] = [];
	for (const entry of entries) {
		const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
		const full = path.join(dir, entry.name);
		if (entry.isDirectory()) out.push(...(await scanFiles(full, rel)));
		else out.push(rel);
	}
	return out;
}

async function contentHash(files: Record<string, string>): Promise<string> {
	const buffer = new Bun.CryptoHasher("sha1");
	for (const rel of Object.keys(files).sort()) {
		buffer.update(rel);
		buffer.update(files[rel]!);
	}
	return buffer.digest("hex").slice(0, 16);
}

/** Embed the collab-web dist into the generated module. Missing dist -> stub. */
export async function generateCollabWebEmbed(repoRoot: string): Promise<void> {
	const distDir = path.join(repoRoot, "packages", "collab-web", "dist");
	const outFile = path.join(repoRoot, "packages", "coding-agent", GENERATED_REL);
	let files: Record<string, string> = {};
	try {
		if (await Bun.file(path.join(distDir, "index.html")).exists()) {
			const rels = await scanFiles(distDir, "");
			const entries = await Promise.all(
				rels.map(async rel => [rel, await Bun.file(path.join(distDir, rel)).arrayBuffer()] as const),
			);
			files = Object.fromEntries(entries.map(([rel, bytes]) => [rel, Buffer.from(bytes).toString("base64")]));
		}
	} catch (err) {
		console.error(`embed-collab-web: failed to read ${distDir}; embedding empty stub`, err);
		files = {};
	}
	const version = await contentHash(files);
	const content = `// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY
// See scripts/embed-collab-web.ts

/** Collab web dist files baked into compiled binaries: relative path -> base64. */
export const EMBEDDED_COLLAB_WEB_FILES: Record<string, string> = ${JSON.stringify(files)};

/** Content hash of the embedded dist; used as the materialization cache key. */
export const EMBEDDED_COLLAB_WEB_VERSION = ${JSON.stringify(version)};
`;
	await Bun.write(outFile, content);
	console.log(`embedded collab-web dist (${Object.keys(files).length} files, v${version}) into ${GENERATED_REL}`);
}

/** Restore the checked-in stub after a binary build. */
export async function resetCollabWebEmbed(repoRoot: string): Promise<void> {
	const outFile = path.join(repoRoot, "packages", "coding-agent", GENERATED_REL);
	await Bun.write(outFile, STUB);
}

if (import.meta.main) {
	const repoRoot = path.resolve(import.meta.dir, "..", "..", "..");
	if (Bun.argv.includes("--reset")) {
		await resetCollabWebEmbed(repoRoot);
	} else {
		await generateCollabWebEmbed(repoRoot);
	}
}
