// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY
// See scripts/embed-collab-web.ts

/** Collab web dist files baked into compiled binaries: relative path -> base64. */
export const EMBEDDED_COLLAB_WEB_FILES: Record<string, string> = {};

/** Content hash of the embedded dist; used as the materialization cache key. */
export const EMBEDDED_COLLAB_WEB_VERSION = "stub";
