import { mkdir } from "node:fs/promises";
import * as os from "node:os";
import * as path from "node:path";
import type {
	AgentTool,
	AgentToolArgStream,
	AgentToolArgStreamInit,
	AgentToolContext,
	AgentToolResult,
	AgentToolUpdateCallback,
	ToolApprovalDecision,
} from "@oh-my-pi/pi-agent-core";
import type { Model, ToolExample } from "@oh-my-pi/pi-ai";
import {
	EditSession,
	editDescription,
	editGrammar,
	editInspect,
	type EditFileOutcome,
	type EditInspection,
	type EditPolicy,
	type EditPreviewBatch,
	type EditUrlResolution,
	type EditWriteRequest,
	type EditWriteResponse,
} from "@oh-my-pi/pi-natives";
import { isEnoent, logger, prompt } from "@oh-my-pi/pi-utils";
import { extractUriScheme, InternalUrlRouter, type ResolveContext, sessionResolveContext } from "../internal-urls";
import { createLspWritethrough, flushLspWritethroughBatch, type WritethroughCallback, writethroughNoop } from "../lsp";
import { type FileDiagnosticsResult } from "@oh-my-pi/pi-tui/tools/lsp";
import { FileChangeType, notifyWorkspaceWatchedFiles } from "../lsp/client";
import { DeferredDiagnostics } from "../lsp/deferred-diagnostics";
import { getDiagnosticsLedger } from "../lsp/diagnostics-ledger";
import type { ToolSession } from "../tools";
import { routeWriteThroughBridge } from "../tools/acp-bridge";
import { strictestApproval, truncateForPrompt } from "../tools/approval";
import {
	deleteFileWithFallback,
	hasFileWriteFallback,
	isPermissionDeniedError,
	writeFileWithFallback,
} from "../tools/file-write-fallback";
import {
	invalidateFsScanAfterDelete,
	invalidateFsScanAfterRename,
	invalidateFsScanAfterWrite,
} from "../tools/fs-cache-invalidation";
import { outputMeta } from "../tools/output-meta";
import { ToolError } from "@oh-my-pi/pi-tui/tools/tool-errors";
import { type EditMode } from "@oh-my-pi/pi-tui/tools/edit";
import { resolveEditMode } from "../utils/edit-mode";
import { attemptEditAutoRepair, type EditAutoRepairOutcome } from "./auto-repair";
import { type AppliedEditSnapshot, createEditBlackboxRecorder } from "./blackbox";
import hashlineCompactPrompt from "./hashline-compact.md" with { type: "text" };
import { getLspBatchRequest } from "../lsp/batch";
import { type EditToolDetails, type EditToolPerFileResult, type Operation } from "@oh-my-pi/pi-tui/tools/edit";
import {
	type ApplyPatchParams,
	applyPatchSchema,
	type HashlineParams,
	hashlineEditParamsSchema,
	type PatchParams,
	patchEditSchema,
	type ReplaceBatchParams,
	type ReplaceParams,
	replaceEditSchema,
	type SloppyParams,
	sloppyEditSchema,
} from "./schemas";
import { getEditStore } from "./store";
import {
	applyInternalEditWrite,
	type EditTargetContext,
	type EditTargetOperation,
	type EditVirtualResourceInput,
	isHostBackedEditTargetPath,
	type ResolvedEditVirtualResource,
	resolveEditVirtualResource,
} from "./target";

import {
	cfgEditBlockAutoGenerated,
	cfgEditEnforceSeenLines,
	cfgEditFuzzyMatch,
	cfgEditFuzzyThreshold,
} from "./settings";
import { cfgLspDiagnosticsDeduplicate, cfgLspDiagnosticsOnEdit, cfgLspFormatOnWrite } from "../lsp/settings";

export type {
	EditRenderContext,
	EditToolDetails,
	EditToolPerFileResult,
	Operation,
	PerFileDiffPreview,
} from "@oh-my-pi/pi-tui/tools/edit";
export * from "./schemas";
export * from "./store";
export { type EditMode } from "@oh-my-pi/pi-tui/tools/edit";

type TInput =
	| typeof replaceEditSchema
	| typeof patchEditSchema
	| typeof hashlineEditParamsSchema
	| typeof applyPatchSchema
	| typeof sloppyEditSchema;

type EditParams = ReplaceParams | ReplaceBatchParams | PatchParams | HashlineParams | ApplyPatchParams | SloppyParams;

type NativeVirtualEditSession = EditSession & {
	preloadVirtualResource(resource: EditVirtualResourceInput): Promise<void>;
};

type ResolvedInternalEditTarget = ResolvedEditVirtualResource["target"];

interface EditSessionState {
	native: NativeVirtualEditSession;
	resolveContext: ResolveContext;
	rawInput: boolean;
	streamedArgs: string;
	pending: Promise<void>;
	finished: boolean;
	preloadError?: unknown;
	targetContext?: Promise<EditTargetContext>;
	preparedIntents: Set<string>;
	internalTargets: Map<string, ResolvedInternalEditTarget>;
}

const PATCH_EXAMPLES = [
	{
		caption: "Create",
		call: { path: "hello.txt", edits: [{ op: "create", diff: "Hello\n" }] },
	},
	{
		caption: "Update",
		call: {
			path: "src/app.py",
			edits: [{ op: "update", diff: "@@ def greet():\n def greet():\n-print('Hi')\n+print('Hello')\n" }],
		},
	},
	{
		caption: "Rename",
		call: {
			path: "src/app.py",
			edits: [{ op: "update", rename: "src/main.py", diff: "@@\n …\n" }],
		},
	},
	{
		caption: "Delete",
		call: { path: "obsolete.txt", edits: [{ op: "delete" }] },
	},
	{
		caption: "Multiple entries",
		note: "All entries in one call apply to the top-level `path`; use separate calls for different files.",
	},
] satisfies readonly ToolExample<PatchParams>[];

const APPLY_PATCH_EXAMPLES = [
	{
		caption: "Apply a combined patch file",
		call: {
			input: '*** Begin Patch\n*** Add File: hello.txt\n+Hello world\n*** Update File: src/app.py\n*** Move to: src/main.py\n@@ def greet():\n-print("Hi")\n+print("Hello, world!")\n*** Delete File: obsolete.txt\n*** End Patch\n',
		},
	},
] satisfies readonly ToolExample<ApplyPatchParams>[];

/**
 * Compact tool description markdown for `mode`, when one exists. TS-side
 * source (not the native addon) so PR CI — which tests against the latest
 * *release* addons — exercises the same rendering production does.
 */
export function editDescriptionCompact(mode: EditMode): string | undefined {
	switch (mode) {
		case "hashline":
			return hashlineCompactPrompt;
		default:
			return undefined;
	}
}

/**
 * Tool description for `mode`, at the density the model's catalog policy
 * selects (`edit-prompt-variant`). Models without the compact variant — or
 * modes that have none — keep the full prompt; both renderings preserve every
 * operation and invariant.
 */
export function resolveEditToolDescription(
	mode: EditMode,
	model: Pick<Model, "editPromptVariant"> | undefined,
): string {
	const source =
		model?.editPromptVariant === "compact"
			? (editDescriptionCompact(mode) ?? editDescription(mode))
			: editDescription(mode);
	return prompt.render(source);
}

/** Builds the LSP writethrough from the current `lsp.*` settings; called per write so changes apply immediately. */
function createEditWritethrough(session: ToolSession): WritethroughCallback {
	const enableLsp = session.enableLsp ?? true;
	const enableDiagnostics = enableLsp && cfgLspDiagnosticsOnEdit.get(session.settings);
	const enableFormat = enableLsp && cfgLspFormatOnWrite.get(session.settings);
	const deduplicate = enableDiagnostics && cfgLspDiagnosticsDeduplicate.get(session.settings);
	return enableLsp
		? createLspWritethrough(session.cwd, {
				enableFormat,
				enableDiagnostics,
				transformDiagnostics: deduplicate
					? (filePath, result) => getDiagnosticsLedger(session).reduce(filePath, result)
					: undefined,
			})
		: writethroughNoop;
}

function operationFromNative(op: string): Operation | undefined {
	return op === "create" || op === "delete" || op === "update" ? op : undefined;
}

function parseDiagnostics(json: string | undefined): FileDiagnosticsResult | undefined {
	if (!json) return undefined;
	try {
		return JSON.parse(json) as FileDiagnosticsResult;
	} catch {
		return undefined;
	}
}

function mergeDiagnosticsWithWarnings(
	diagnostics: FileDiagnosticsResult | undefined,
	warnings: readonly string[],
): FileDiagnosticsResult | undefined {
	if (warnings.length === 0) return diagnostics;
	const warningMessages = warnings.map(warning => `patch: ${warning}`);
	if (!diagnostics) {
		return {
			server: "patch",
			messages: warningMessages,
			summary: `Patch warnings: ${warnings.length}`,
			errored: false,
		};
	}
	return {
		...diagnostics,
		messages: [...warningMessages, ...diagnostics.messages],
		summary: `${diagnostics.summary}; Patch warnings: ${warnings.length}`,
	};
}

function toPerFileResult(file: EditFileOutcome, mode: EditMode): EditToolPerFileResult {
	let diagnostics = parseDiagnostics(file.diagnosticsJson);
	if (mode === "patch" || mode === "apply_patch") {
		diagnostics = mergeDiagnosticsWithWarnings(diagnostics, file.warnings);
	}
	const resultPath = file.moveTo ?? file.path;
	return {
		path: resultPath,
		diff: file.diff,
		firstChangedLine: file.firstChangedLine,
		diagnostics,
		op: operationFromNative(file.op),
		move: file.moveTo,
		sourcePath: file.moveTo ? file.path : undefined,
		oldText: file.oldText,
		newText: file.newText,
		snapshotsPruned: file.snapshotsPruned || undefined,
		meta: outputMeta()
			.diagnostics(diagnostics?.summary ?? "", diagnostics?.messages ?? [])
			.get(),
	};
}

function aggregateDetails(files: readonly EditFileOutcome[], mode: EditMode): EditToolDetails | undefined {
	if (files.length === 0) return undefined;
	const perFileResults = files.map(file => toPerFileResult(file, mode));
	if (perFileResults.length === 1) {
		const [file] = perFileResults;
		return {
			diff: file.diff,
			firstChangedLine: file.firstChangedLine,
			diagnostics: file.diagnostics,
			op: file.op,
			move: file.move,
			sourcePath: file.sourcePath,
			path: file.path,
			oldText: file.oldText,
			newText: file.newText,
			snapshotsPruned: file.snapshotsPruned,
			meta: file.meta,
		};
	}
	return {
		diff: perFileResults
			.map(file => file.diff)
			.filter(Boolean)
			.join("\n"),
		firstChangedLine: perFileResults.find(file => file.firstChangedLine !== undefined)?.firstChangedLine,
		perFileResults: capPerFileSnapshots(perFileResults),
	};
}

/**
 * Combined `oldText` + `newText` character budget shared across a multi-file
 * result. The engine already prunes each file on its own; this keeps a
 * many-small-files batch from accumulating unbounded snapshot bytes in the
 * session JSONL (#3787). Early entries keep their diff visualization; later
 * ones degrade to text-only.
 */
const MAX_EDIT_SNAPSHOT_TEXT_CHARS = 32_768;

function capPerFileSnapshots(entries: EditToolPerFileResult[]): EditToolPerFileResult[] {
	let remaining = MAX_EDIT_SNAPSHOT_TEXT_CHARS;
	return entries.map(entry => {
		const kept = (entry.oldText?.length ?? 0) + (entry.newText?.length ?? 0);
		if (kept === 0) return entry;
		if (kept <= remaining) {
			remaining -= kept;
			return entry;
		}
		const { oldText: _old, newText: _new, ...rest } = entry;
		return { ...rest, snapshotsPruned: true };
	});
}

async function mkdirAllowingFallback(directory: string): Promise<void> {
	try {
		await mkdir(directory, { recursive: true });
	} catch (error) {
		if (!hasFileWriteFallback() || !isPermissionDeniedError(error)) throw error;
	}
}

/** Memoized native inspection, tagged onto the streamed args object it describes. */
const kInspection = Symbol("edit.inspection");

interface InspectedArgs {
	[kInspection]?: { mode: EditMode; inspection: EditInspection };
}

function bytesEqual(left: Uint8Array, right: Uint8Array): boolean {
	if (left.byteLength !== right.byteLength) return false;
	for (let index = 0; index < left.byteLength; index++) {
		if (left[index] !== right[index]) return false;
	}
	return true;
}

/**
 * Approval tier of the raw, untrusted payload, scanned before — and
 * independently of — the native parser's attribution.
 *
 * `#inspect` reports only the sections the native parser can attribute, so a
 * payload carrying a target in a form it cannot parse (or one whose section
 * header is a selector-suffixed URL) would otherwise reach the write tier.
 * {@link InternalUrlRouter.readTier} is the router's fail-closed substring
 * scan over every registered `scheme://` (mirroring the read/grep tools): a
 * literal `ssh://` anywhere is exec, and over-matching only over-prompts.
 */
function approvalPayloadTier(args: unknown): ToolApprovalDecision {
	const router = InternalUrlRouter.instance();
	if (typeof args === "string") return router.readTier(args);
	const record = args && typeof args === "object" ? (args as Record<string, unknown>) : {};
	const fields = [record.input, record.path].filter((value): value is string => typeof value === "string");
	return strictestApproval(fields.map(field => router.readTier(field)));
}

export class EditTool implements AgentTool<TInput> {
	readonly name = "edit";
	readonly label = "Edit";
	readonly loadMode = "essential";
	readonly concurrency = "exclusive";
	readonly strict = true;

	readonly #editMode?: EditMode;
	readonly #deferredDiagnostics: DeferredDiagnostics;
	readonly #sessions = new Map<string, EditSessionState>();
	readonly #streamedArgs = new Map<string, string>();

	constructor(
		private readonly session: ToolSession,
		mode?: EditMode,
	) {
		this.#editMode = mode;
		this.#deferredDiagnostics = new DeferredDiagnostics(session);
	}

	get mode(): EditMode {
		return this.#editMode ?? resolveEditMode(this.session);
	}

	get description(): string {
		return resolveEditToolDescription(this.mode, this.session.getActiveModel?.());
	}

	get parameters(): TInput {
		switch (this.mode) {
			case "replace":
				return replaceEditSchema;
			case "patch":
				return patchEditSchema;
			case "apply_patch":
				return applyPatchSchema;
			case "hashline":
				return hashlineEditParamsSchema;
			case "sloppy":
				return sloppyEditSchema;
		}
	}

	get examples(): readonly ToolExample[] | undefined {
		if (this.mode === "patch") return PATCH_EXAMPLES;
		if (this.mode === "apply_patch") return APPLY_PATCH_EXAMPLES;
		return undefined;
	}

	get customFormat(): { syntax: "lark"; definition: string } | undefined {
		const definition = editGrammar(this.mode);
		return definition === null ? undefined : { syntax: "lark", definition };
	}

	get customWireName(): string | undefined {
		return this.mode === "apply_patch" ? "apply_patch" : undefined;
	}

	/**
	 * Strictest write decision ({@link strictestApproval}) over every path the payload writes:
	 * section targets plus move/rename destinations. "write" while no target is known.
	 *
	 * Remote SSH edits open an outbound connection and run a remote shell to move the
	 * file (same tier as the exec-gated `ssh` tool and `write`), so they must not be
	 * classified by the internal-resource read/write split below. The payload is scanned
	 * before the parsed targets: `#inspect` only reports sections it can attribute, and a
	 * payload it cannot parse (or whose section names a `ssh://` selector) must still fail
	 * closed at exec. A `ssh://` entry riding along with a workspace path stays exec —
	 * every section of a multi-section payload is written.
	 */
	readonly approval = (args: unknown): ToolApprovalDecision => {
		const { paths, fileOps } = this.#inspect(args);
		const targets = [...paths];
		for (const op of fileOps) if (op.kind === "move" && op.to !== undefined) targets.push(op.to);
		const router = InternalUrlRouter.instance();
		// The payload scan runs even when the projection attributed no target: an
		// unattributable payload is exactly the case that must fail closed.
		const decisions: ToolApprovalDecision[] = [
			approvalPayloadTier(args),
			...targets.map(target => router.writeTier(target, undefined, this.session)),
		];
		if (targets.length === 0) decisions.push("write");
		return strictestApproval(decisions);
	};

	readonly formatApprovalDetails = (args: unknown): string[] => {
		const { paths, fileOps } = this.#inspect(args);
		const lines = paths.map(target => `File: ${truncateForPrompt(target)}`);
		for (const op of fileOps) {
			if (op.kind === "move" && op.to !== undefined) {
				lines.push(`Move: ${truncateForPrompt(op.path)} → ${truncateForPrompt(op.to)}`);
			}
		}
		return lines.length === 0 ? ["File: (unknown)"] : lines;
	};

	matcherDigest(args: unknown): string | undefined {
		const digest = this.#inspect(args)
			.entries.map(entry => entry.digest)
			.filter(Boolean)
			.join("\n");
		return digest || undefined;
	}

	matcherPaths(args: unknown): readonly string[] | undefined {
		const inspection = this.#inspect(args);
		const paths = inspection.entries.length > 0 ? inspection.entries.map(entry => entry.path) : inspection.paths;
		return paths.length > 0 ? paths : undefined;
	}

	matcherEntries(args: unknown): readonly { path: string; digest: string }[] | undefined {
		const entries = this.#inspect(args).entries;
		return entries.length > 0 ? entries : undefined;
	}

	openArgStream(init: AgentToolArgStreamInit): AgentToolArgStream {
		this.#sessions.get(init.toolCallId)?.native.close();
		this.#streamedArgs.delete(init.toolCallId);
		// A call that arrived through the custom-tool wire streams the payload
		// verbatim; JSON function calls stream JSON text.
		const rawInput = init.customWireName !== undefined;
		const state = this.#openSession(rawInput, undefined, (error, batch) => {
			if (error) {
				logger.debug("Native edit preview failed", { error: error.message, toolCallId: init.toolCallId });
				return;
			}
			init.emit(batch);
		});
		this.#sessions.delete(init.toolCallId);
		this.#sessions.set(init.toolCallId, state);
		while (this.#sessions.size > 32) {
			const oldestId = this.#sessions.keys().next().value;
			if (oldestId === undefined) break;
			this.#sessions.get(oldestId)?.native.close();
			this.#sessions.delete(oldestId);
			this.#streamedArgs.delete(oldestId);
		}
		return {
			push: delta => {
				state.streamedArgs += delta;
				const inspection = this.#inspectSerialized(
					state.rawInput ? JSON.stringify({ input: state.streamedArgs }) : state.streamedArgs,
				);
				state.pending = state.pending.then(async () => {
					try {
						await this.#preloadInspection(state, inspection, undefined, false);
					} catch {
						// A partial path may not resolve yet. The next delta retries it,
						// and the complete payload is resolved strictly before apply.
					}
					state.native.push(delta);
				});
			},
			end: args => {
				const inspection =
					args === undefined
						? this.#inspectSerialized(
								state.rawInput ? JSON.stringify({ input: state.streamedArgs }) : state.streamedArgs,
							)
						: this.#inspect(args);
				state.pending = state.pending.then(async () => {
					try {
						await this.#preloadInspection(state, inspection, undefined, true);
						state.preloadError = undefined;
					} catch (error) {
						state.preloadError = error;
					}
					state.native.finish();
					state.finished = true;
				});
				this.#streamedArgs.set(init.toolCallId, JSON.stringify(args));
			},
			cancel: () => {
				state.native.close();
				if (this.#sessions.get(init.toolCallId) === state) this.#sessions.delete(init.toolCallId);
				this.#streamedArgs.delete(init.toolCallId);
			},
		};
	}

	async execute(
		toolCallId: string,
		params: EditParams,
		signal?: AbortSignal,
		_onUpdate?: AgentToolUpdateCallback<EditToolDetails, TInput>,
		context?: AgentToolContext,
	): Promise<AgentToolResult<EditToolDetails, TInput>> {
		let state = this.#sessions.get(toolCallId);
		const argsJson = JSON.stringify(params);
		if (state && this.#streamedArgs.get(toolCallId) !== argsJson) {
			state.native.close();
			this.#sessions.delete(toolCallId);
			state = undefined;
		}
		this.#streamedArgs.delete(toolCallId);
		const streamed = Boolean(state);
		if (state) {
			// The streamed session was opened before any signal existed; URL targets
			// resolved during apply honor this call's abort.
			state.resolveContext.signal = signal;
		} else {
			// No deltas were streamed (non-streaming provider, inline recovery,
			// Cursor batch frames), or a pre-execution hook revised the arguments:
			// the parsed args are the whole effective payload.
			state = this.#openSession(false, signal);
		}
		await state.pending;
		try {
			await this.#preloadInspection(state, this.#inspect(params), signal, true);
			state.preloadError = undefined;
		} catch (error) {
			state.preloadError = error;
		}
		if (state.preloadError) {
			state.native.close();
			if (this.#sessions.get(toolCallId) === state) this.#sessions.delete(toolCallId);
			throw state.preloadError;
		}
		if (!streamed) state.native.setArgsJson(JSON.stringify(params));
		if (!state.finished) {
			state.native.finish();
			state.finished = true;
		}
		const batch = getLspBatchRequest(context?.toolCall);
		let outcome;
		try {
			outcome = await state.native.apply(
				{ lspBatchId: batch?.id, lspFlush: batch?.flush ?? false },
				(_error, request) => this.#write(state, request, signal),
			);
			if (outcome.isError && batch?.flush) {
				await flushLspWritethroughBatch(batch.id, this.session.cwd, signal);
			}
		} catch (error) {
			if (batch?.flush) await flushLspWritethroughBatch(batch.id, this.session.cwd, signal);
			throw error;
		} finally {
			state.native.close();
			if (this.#sessions.get(toolCallId) === state) this.#sessions.delete(toolCallId);
			this.#streamedArgs.delete(toolCallId);
		}

		if (outcome.isError) {
			return { content: [{ type: "text", text: outcome.text }], isError: true };
		}

		const details = aggregateDetails(outcome.files, this.mode);
		const result: AgentToolResult<EditToolDetails, TInput> = {
			content: [{ type: "text", text: outcome.text }],
			...(details ? { details } : {}),
		};
		const record = createEditBlackboxRecorder(this.session, this.mode, params);
		const notes: string[] = [];
		for (const file of outcome.files) {
			if (!file.parseRegressed || file.oldText === undefined || file.newText === undefined) continue;
			if (state.internalTargets.has(file.path) || (file.moveTo && state.internalTargets.has(file.moveTo))) continue;
			const snapshot: AppliedEditSnapshot = {
				path: file.moveTo ?? file.path,
				prev: file.oldText,
				next: file.newText,
			};
			try {
				await record?.(snapshot);
			} catch {
				// Blackbox recording is diagnostic only.
			}
			const display = path.relative(this.session.cwd, snapshot.path) || snapshot.path;
			let repaired: EditAutoRepairOutcome | undefined;
			try {
				repaired = await attemptEditAutoRepair({
					session: this.session,
					snapshot,
					writethrough: createEditWritethrough(this.session),
					signal,
				});
				if (repaired) getEditStore(this.session).invalidate(snapshot.path);
			} catch (error) {
				logger.warn("Edit auto-repair failed", {
					path: snapshot.path,
					error: error instanceof Error ? error.message : String(error),
				});
			}
			notes.push(
				repaired
					? `Note: ${display} stopped parsing after this edit; an automatic syntax repair (${repaired.model}) was applied on top:\n${repaired.diff}\nReview the repaired region; adjust it if the repair guessed wrong.`
					: `Warning: ${display} no longer parses after this edit. The change was applied; re-read the edited region and fix the syntax, or revert if unintended.`,
			);
		}
		if (notes.length > 0) result.content.push({ type: "text", text: notes.join("\n\n") });
		return result;
	}

	/**
	 * TTSR asks `matcherPaths` and `matcherEntries` (and approval asks again)
	 * for the same streamed args object on every delta, and the native inspect
	 * re-parses the whole payload each time; the result is tagged onto the args
	 * so repeat lookups for one object pay once.
	 */
	#inspect(args: unknown): EditInspection {
		const tagged = typeof args === "object" && args !== null ? (args as InspectedArgs) : undefined;
		const cached = tagged?.[kInspection];
		if (cached?.mode === this.mode) return cached.inspection;
		let inspection: EditInspection;
		try {
			inspection = editInspect(this.mode, JSON.stringify(args ?? {}));
		} catch {
			inspection = { paths: [], entries: [], fileOps: [] };
		}
		if (tagged) tagged[kInspection] = { mode: this.mode, inspection };
		return inspection;
	}

	#inspectSerialized(args: string): EditInspection {
		try {
			return editInspect(this.mode, args);
		} catch {
			return { paths: [], entries: [], fileOps: [] };
		}
	}

	async #targetContext(state: EditSessionState, signal?: AbortSignal): Promise<EditTargetContext> {
		state.targetContext ??= (async () => ({
			cwd: this.session.cwd,
			localProtocolOptions: this.session.localProtocolOptions,
			sshHosts: await this.session.getSessionSshHosts?.(),
		}))();
		const context = await state.targetContext;
		return signal ? { ...context, signal } : context;
	}

	async #preloadInspection(
		state: EditSessionState,
		inspection: EditInspection,
		signal: AbortSignal | undefined,
		refresh: boolean,
	): Promise<void> {
		const intents = new Map<
			string,
			{ path: string; op: EditTargetOperation; move?: string; enforcePlanMode?: boolean }
		>();
		for (const path of inspection.paths) intents.set(path, { path, op: "update" });
		for (const entry of inspection.entries) {
			if (!intents.has(entry.path)) intents.set(entry.path, { path: entry.path, op: "update" });
		}
		for (const fileOp of inspection.fileOps) {
			if (fileOp.kind === "delete") {
				intents.set(fileOp.path, { path: fileOp.path, op: "delete" });
			} else if (fileOp.kind === "move" && fileOp.to) {
				intents.set(fileOp.path, { path: fileOp.path, op: "update", move: fileOp.to });
				intents.set(fileOp.to, { path: fileOp.to, op: "create", enforcePlanMode: false });
			}
		}
		if (intents.size === 0) return;

		const context = await this.#targetContext(state, signal);
		const pending: Array<
			Promise<{
				intentKey: string;
				resolved: ResolvedEditVirtualResource | undefined;
			}>
		> = [];
		for (const intent of intents.values()) {
			const intentKey = JSON.stringify([intent.path, intent.op, intent.move ?? null]);
			if (!refresh && state.preparedIntents.has(intentKey)) continue;
			if (!isHostBackedEditTargetPath(intent.path)) {
				state.preparedIntents.add(intentKey);
				continue;
			}
			pending.push(
				resolveEditVirtualResource(this.session, intent.path, {
					op: intent.op,
					move: intent.move,
					signal,
					enforcePlanMode: intent.enforcePlanMode,
					context,
				}).then(resolved => ({ intentKey, resolved })),
			);
		}
		const resources = await Promise.all(pending);
		for (const { intentKey, resolved } of resources) {
			if (resolved) {
				await state.native.preloadVirtualResource(resolved.resource);
				state.internalTargets.set(resolved.target.canonicalPath, resolved.target);
			}
			state.preparedIntents.add(intentKey);
		}
	}

	/**
	 * Open a native session whose internal-URL targets resolve through the router
	 * with one {@link ResolveContext} built for the session's lifetime. Targets the
	 * host materializes itself (remote and virtual schemes) are preloaded per
	 * {@link EditTool.#preloadInspection}; the router callback answers the rest.
	 */
	#openSession(
		rawInput: boolean,
		signal?: AbortSignal,
		onPreview?: (error: Error | null, batch: EditPreviewBatch) => void,
	): EditSessionState {
		const resolveContext = sessionResolveContext(this.session, { signal });
		const native = new EditSession(
			getEditStore(this.session),
			this.#policy(rawInput, resolveContext),
			onPreview,
			(_error, url) => this.#resolveUrl(url, resolveContext),
		) as NativeVirtualEditSession;
		return {
			native,
			resolveContext,
			rawInput,
			streamedArgs: "",
			pending: Promise.resolve(),
			preparedIntents: new Set(),
			internalTargets: new Map(),
			finished: false,
		};
	}

	#policy(rawInput: boolean, context: ResolveContext): EditPolicy {
		const router = InternalUrlRouter.instance();
		const specs = router.specs();
		const urlAliasSchemes: string[] = [];
		for (const [scheme, spec] of specs) if (spec.singleSlashAlias) urlAliasSchemes.push(scheme);
		return {
			cwd: this.session.cwd,
			mode: this.mode,
			allowFuzzy: cfgEditFuzzyMatch.get(this.session.settings),
			fuzzyThreshold: cfgEditFuzzyThreshold.get(this.session.settings),
			enforceSeenLines: cfgEditEnforceSeenLines.get(this.session.settings),
			blockAutoGenerated: cfgEditBlockAutoGenerated.get(this.session.settings),
			planActive: this.session.getPlanModeState?.()?.enabled ?? false,
			urlSchemes: [...specs.keys()],
			urlAliasSchemes,
			planWritableRoots: router.sandboxRoots(context),
			homeDir: os.homedir(),
			rawInput,
		};
	}

	/**
	 * Host answer for one internal-URL edit target: its backing file, or a model-facing refusal.
	 * Only file-written mutable schemes ({@link InternalUrlRouter.fileWritable}) are editable;
	 * handler-owned writes (agent:// messages, proc:// stdin, ...) never patch their backing file.
	 * A line/partial selector is refused ({@link InternalUrlRouter.peelWriteSelector}): edits
	 * address whole files.
	 *
	 * Host materialized it earlier (`#preloadInspection` → `preloadVirtualResource`), so
	 * this callback only ever answers targets the preload pass missed.
	 */
	async #resolveUrl(url: string, context: ResolveContext): Promise<EditUrlResolution> {
		const router = InternalUrlRouter.instance();
		try {
			const target = router.peelWriteSelector(url, "edit");
			const scheme = extractUriScheme(target);
			const spec = scheme === undefined ? undefined : router.spec(scheme);
			if (!spec) return { error: `Unknown internal URL: ${url}`, planWritable: false };
			if (!router.fileWritable(target)) {
				const reason = spec.write?.via === "handler" ? "is written through `write`, not edited" : "is read-only";
				return { error: `${url} ${reason}`, planWritable: false };
			}
			const located = await router.locate(target, context, { create: true });
			return { path: located ?? undefined, planWritable: spec.write?.scope === "sandbox" };
		} catch (error) {
			return { error: error instanceof Error ? error.message : String(error), planWritable: false };
		}
	}

	async #write(state: EditSessionState, request: EditWriteRequest, signal?: AbortSignal): Promise<EditWriteResponse> {
		const source = state.internalTargets.get(request.path);
		const destination = request.moveTo ? state.internalTargets.get(request.moveTo) : undefined;
		const sourceIsInternal = isHostBackedEditTargetPath(request.path);
		const destinationIsInternal = request.moveTo ? isHostBackedEditTargetPath(request.moveTo) : false;
		if (source || destination || sourceIsInternal || destinationIsInternal) {
			if (!source) {
				throw new ToolError("Remote/local edit moves are not supported", { path: request.displayPath });
			}
			if (request.op === "move" && !destination) {
				throw new ToolError("Remote/local edit moves are not supported", { path: request.displayPath });
			}
			const written = await applyInternalEditWrite(
				source,
				request,
				await this.#targetContext(state, signal),
				destination,
			);
			return { written };
		}

		if (request.op === "delete") {
			await deleteFileWithFallback(request.path, Bun.file(request.path));
			if (this.session.enableLsp ?? true) {
				await notifyWorkspaceWatchedFiles(
					this.session.cwd,
					[{ filePath: request.path, type: FileChangeType.Deleted }],
					signal,
				);
			}
			invalidateFsScanAfterDelete(request.path);
			this.session.bumpFileMutationVersion?.(request.path);
			const diagnostics =
				request.flushLsp && request.lspBatchId
					? await flushLspWritethroughBatch(request.lspBatchId, this.session.cwd, signal)
					: undefined;
			return {
				written: "",
				diagnosticsJson: diagnostics ? JSON.stringify(diagnostics) : undefined,
			};
		}

		if (request.content === undefined) {
			throw new ToolError(`Native edit ${request.op} request omitted content`, { path: request.path });
		}

		if (request.op === "move") {
			if (!request.moveTo) {
				throw new ToolError("Native edit move request omitted destination", { path: request.path });
			}
			await mkdirAllowingFallback(path.dirname(request.moveTo));
			await writeFileWithFallback(request.moveTo, request.content);
			await deleteFileWithFallback(request.path, Bun.file(request.path));
			if (this.session.enableLsp ?? true) {
				await notifyWorkspaceWatchedFiles(
					this.session.cwd,
					[
						{ filePath: request.path, type: FileChangeType.Deleted },
						{ filePath: request.moveTo, type: FileChangeType.Created },
					],
					signal,
				);
			}
			invalidateFsScanAfterRename(request.path, request.moveTo);
			this.session.bumpFileMutationVersion?.(request.path);
			this.session.bumpFileMutationVersion?.(request.moveTo);
			const diagnostics =
				request.flushLsp && request.lspBatchId
					? await flushLspWritethroughBatch(request.lspBatchId, this.session.cwd, signal)
					: undefined;
			return {
				written: request.content,
				diagnosticsJson: diagnostics ? JSON.stringify(diagnostics) : undefined,
			};
		}

		const bridge = await routeWriteThroughBridge(
			this.session,
			request.displayPath,
			request.path,
			request.content,
			signal,
		);
		if (bridge) return { written: bridge.text };

		let preWriteBytes: Uint8Array | undefined;
		if (request.op === "update") {
			try {
				preWriteBytes = await Bun.file(request.path).bytes();
			} catch (error) {
				if (!isEnoent(error)) throw error;
			}
		} else if (request.op === "create") {
			await mkdirAllowingFallback(path.dirname(request.path));
		}

		const diagnostics = await createEditWritethrough(this.session)(
			request.path,
			request.content,
			signal,
			Bun.file(request.path),
			request.lspBatchId ? { id: request.lspBatchId, flush: request.flushLsp } : undefined,
			destination => (destination === request.path ? this.#deferredDiagnostics.begin(request.path) : undefined),
		);

		if (preWriteBytes !== undefined) {
			const requestedBytes = new TextEncoder().encode(request.content);
			if (!bytesEqual(requestedBytes, preWriteBytes)) {
				let postWriteBytes: Uint8Array | undefined;
				try {
					postWriteBytes = await Bun.file(request.path).bytes();
				} catch (error) {
					if (!isEnoent(error)) throw error;
				}
				if (postWriteBytes !== undefined && bytesEqual(postWriteBytes, preWriteBytes)) {
					throw new ToolError(
						`edit appeared successful but file content did not change on disk: ${request.displayPath}`,
						{ path: request.path },
					);
				}
			}
		}

		invalidateFsScanAfterWrite(request.path);
		this.session.bumpFileMutationVersion?.(request.path);
		return {
			written: diagnostics.finalContent,
			diagnosticsJson: diagnostics.diagnostics ? JSON.stringify(diagnostics.diagnostics) : undefined,
		};
	}
}
